### ISSUE TITLE
Yarn PnP compatibility?

### ISSUE THREAD

**Issue by bencmbrook** [wooorm/load-plugin#15]
I believe the issue described here (https://github.com/remarkjs/remark-language-server/issues/6#issuecomment-1323081856) is a result of an assumption that packages are stored in a `node_modules` directory. 

I tried running `resolvePlugin` and `loadPlugin` against my project and got the following error

```
% yarn node test.mjs

Error: Cannot find package 'lint' imported from /<mycwd>/
    at new NodeError (file:///<mycwd>/.yarn/cache/import-meta-resolve-npm-2.1.0-fcf1208127-4554ea5e2d.zip/node_modules/import-meta-resolve/lib/errors.js:276:5)
    at packageResolve (file:///<mycwd>/.yarn/cache/import-meta-resolve-npm-2.1.0-fcf1208127-4554ea5e2d.zip/node_modules/import-meta-resolve/lib/resolve.js:1060:9)
    at moduleResolve (file:///<mycwd>/.yarn/cache/import-meta-resolve-npm-2.1.0-fcf1208127-4554ea5e2d.zip/node_modules/import-meta-resolve/lib/resolve.js:1117:20)
    at defaultResolve (file:///<mycwd>/.yarn/cache/import-meta-resolve-npm-2.1.0-fcf1208127-4554ea5e2d.zip/node_modules/import-meta-resolve/lib/resolve.js:1266:15)
    at resolve (file:///<mycwd>/.yarn/cache/import-meta-resolve-npm-2.1.0-fcf1208127-4554ea5e2d.zip/node_modules/import-meta-resolve/index.js:29:12)
    at attempt (file:///<mycwd>/.yarn/cache/load-plugin-npm-5.1.0-5695bc6a89-d450c9a083.zip/node_modules/load-plugin/index.js:167:15)
    at resolvePlugin (file:///<mycwd>/.yarn/cache/load-plugin-npm-5.1.0-5695bc6a89-d450c9a083.zip/node_modules/load-plugin/index.js:148:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///<mycwd>/test.mjs:5:17 {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

where `test.mjs` is

```js
import { loadPlugin, resolvePlugin } from 'load-plugin';

(async () => {
  try {
    console.log(await resolvePlugin('lint', { prefix: 'remark' }));
  } catch (error) {
    console.error(error);
  }
})();
```

**Comment by bencmbrook** [comment]
Actually this is `import-meta-resolve` https://github.com/wooorm/import-meta-resolve/issues/10
